language: node_js
node_js:
 - "10.0.0"
 - "12.18.2"
before_script:
 - npm install -g node-gyp
 - cd src
 - cd third-party/zlib
 - ./configure
 - cd ../libpng/
 - ./configure
 - cd ../jpeg/
 - ./configure
 - cd ../..
 - node-gyp configure&&node-gyp build

